name: build

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/checkout@v2
    - run: go run ./cmd/render
    - run: |-
        git config --global user.email "github-actions@routerd.net"
        git config --global user.name "github-actions"

        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git add www/
        git commit -m "rebuild site"
        git push github HEAD:${GITHUB_REF}
